function [trainedClassifier, validationAccuracy] = baggedtree(trainingData,config)
MaxNumSplits = config(1);
NumLearningCycles = config(2);
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: a table containing the same predictor and response
%       columns as imported into the app.
%
%  Output:
%      trainedClassifier: a struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: a function to make predictions on new
%       data.
%
%      validationAccuracy: a double containing the accuracy in percent. In
%       the app, the History list displays this overall accuracy score for
%       each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   yfit = trainedClassifier.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 30-Nov-2018 12:55:15


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'E_1', 'E_2', 'E_3', 'E_4', 'E_5', 'Era_1', 'Era_2', 'Era_3', 'Era_4', 'Era_5', 'Erd_1', 'Erd_2', 'Erd_3', 'Erd_4', 'Erd_5', 'Erd_6', 'Erd_7', 'Erd_8', 'Erd_9', 'Erd_10', 'Erd_11', 'Erd_12', 'Erd_13', 'Erd_14', 'Erd_15'};
predictors = inputTable(:, predictorNames);
response = inputTable.mainclass;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
template = templateTree(...
    'MaxNumSplits', MaxNumSplits);
classificationEnsemble = fitcensemble(...
    predictors, ...
    response, ...
    'Method', 'Bag', ...
    'NumLearningCycles', NumLearningCycles, ...
    'Learners', template, ...
    'ClassNames', categorical({'close eye'; 'eye brown'; 'eye left'; 'eye right'; 'open eye'; 'smile'; 'thinking backward'; 'thinking foward'; 'thinking left'; 'thinking right'; 'normal'}, {'close eye' 'eye brown' 'eye left' 'eye right' 'open eye' 'smile' 'thinking backward' 'thinking foward' 'thinking left' 'thinking right' 'normal'}));

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
ensemblePredictFcn = @(x) predict(classificationEnsemble, x);
trainedClassifier.predictFcn = @(x) ensemblePredictFcn(predictorExtractionFcn(x));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'E_1', 'E_2', 'E_3', 'E_4', 'E_5', 'Era_1', 'Era_2', 'Era_3', 'Era_4', 'Era_5', 'Erd_1', 'Erd_2', 'Erd_3', 'Erd_4', 'Erd_5', 'Erd_6', 'Erd_7', 'Erd_8', 'Erd_9', 'Erd_10', 'Erd_11', 'Erd_12', 'Erd_13', 'Erd_14', 'Erd_15'};
trainedClassifier.ClassificationEnsemble = classificationEnsemble;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2018b.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  yfit = c.predictFcn(T) \nreplacing ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'E_1', 'E_2', 'E_3', 'E_4', 'E_5', 'Era_1', 'Era_2', 'Era_3', 'Era_4', 'Era_5', 'Erd_1', 'Erd_2', 'Erd_3', 'Erd_4', 'Erd_5', 'Erd_6', 'Erd_7', 'Erd_8', 'Erd_9', 'Erd_10', 'Erd_11', 'Erd_12', 'Erd_13', 'Erd_14', 'Erd_15'};
predictors = inputTable(:, predictorNames);
response = inputTable.mainclass;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Set up holdout validation
cvp = cvpartition(response, 'Holdout', 0.25);
trainingPredictors = predictors(cvp.training, :);
trainingResponse = response(cvp.training, :);
trainingIsCategoricalPredictor = isCategoricalPredictor;

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
template = templateTree(...
    'MaxNumSplits', MaxNumSplits);
classificationEnsemble = fitcensemble(...
    trainingPredictors, ...
    trainingResponse, ...
    'Method', 'Bag', ...
    'NumLearningCycles', NumLearningCycles, ...
    'Learners', template, ...
    'ClassNames', categorical({'close eye'; 'eye brown'; 'eye left'; 'eye right'; 'open eye'; 'smile'; 'thinking backward'; 'thinking foward'; 'thinking left'; 'thinking right'; 'normal'}, {'close eye' 'eye brown' 'eye left' 'eye right' 'open eye' 'smile' 'thinking backward' 'thinking foward' 'thinking left' 'thinking right' 'normal'}));

% Create the result struct with predict function
ensemblePredictFcn = @(x) predict(classificationEnsemble, x);
validationPredictFcn = @(x) ensemblePredictFcn(x);

% Add additional fields to the result struct


% Compute validation predictions
validationPredictors = predictors(cvp.test, :);
validationResponse = response(cvp.test, :);
[validationPredictions, validationScores] = validationPredictFcn(validationPredictors);

% Compute validation accuracy
correctPredictions = (validationPredictions == validationResponse);
isMissing = ismissing(validationResponse);
correctPredictions = correctPredictions(~isMissing);
validationAccuracy = sum(correctPredictions)/length(correctPredictions);
